# Generated by Django 4.2.27 on 2026-06-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_role_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="recovery_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="recovery_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
