# Generated by Django 4.2.27 on 2026-06-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_customuser_recovery_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
